### ISSUE TITLE
date in output

### ISSUE THREAD

**Issue by donpdonp** [atbrask/CMS50Dplus#1]
thanks for the script!  can the output CSV include the time of day? its difficult to plot otherwise.

**Comment by atbrask** [comment]
Thanks for your feedback. I have added a time column to the output CSV for both live and recorded data. In the latter case you'll have to give it a start time, as the oximeter doesn't provide any timestamps.

Please let me know how the new version works out for you.

**Comment by donpdonp** [comment]
that works great. thanks very much for this script!
